# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_minutiae_classificator(object):
    def setupUi(self, minutiae_classificator):
        minutiae_classificator.setObjectName("minutiae_classificator")
        minutiae_classificator.resize(968, 709)
        minutiae_classificator.setToolTipDuration(0)
        self.application = QtWidgets.QWidget(minutiae_classificator)
        self.application.setObjectName("application")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.application)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.settings = QtWidgets.QVBoxLayout()
        self.settings.setSpacing(6)
        self.settings.setObjectName("settings")
        self.settings_layout = QtWidgets.QVBoxLayout()
        self.settings_layout.setSpacing(6)
        self.settings_layout.setObjectName("settings_layout")
        self.label_section_settings = QtWidgets.QLabel(self.application)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_section_settings.setFont(font)
        self.label_section_settings.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_section_settings.setObjectName("label_section_settings")
        self.settings_layout.addWidget(self.label_section_settings)
        self.label_architectures = QtWidgets.QLabel(self.application)
        self.label_architectures.setObjectName("label_architectures")
        self.settings_layout.addWidget(self.label_architectures)
        self.button_coarse_net = QtWidgets.QPushButton(self.application)
        self.button_coarse_net.setObjectName("button_coarse_net")
        self.settings_layout.addWidget(self.button_coarse_net)
        self.button_fine_net = QtWidgets.QPushButton(self.application)
        self.button_fine_net.setObjectName("button_fine_net")
        self.settings_layout.addWidget(self.button_fine_net)
        self.button_classify_net = QtWidgets.QPushButton(self.application)
        self.button_classify_net.setObjectName("button_classify_net")
        self.settings_layout.addWidget(self.button_classify_net)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.settings_layout.addItem(spacerItem)
        self.label_load_network = QtWidgets.QLabel(self.application)
        self.label_load_network.setObjectName("label_load_network")
        self.settings_layout.addWidget(self.label_load_network)
        self.button_load_network = QtWidgets.QPushButton(self.application)
        self.button_load_network.setObjectName("button_load_network")
        self.settings_layout.addWidget(self.button_load_network)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.settings_layout.addItem(spacerItem1)
        self.label_do_the_job = QtWidgets.QLabel(self.application)
        self.label_do_the_job.setObjectName("label_do_the_job")
        self.settings_layout.addWidget(self.label_do_the_job)
        self.button_choose_image = QtWidgets.QPushButton(self.application)
        self.button_choose_image.setObjectName("button_choose_image")
        self.settings_layout.addWidget(self.button_choose_image)
        self.button_extract = QtWidgets.QPushButton(self.application)
        self.button_extract.setObjectName("button_extract")
        self.settings_layout.addWidget(self.button_extract)
        self.button_classify = QtWidgets.QPushButton(self.application)
        self.button_classify.setObjectName("button_classify")
        self.settings_layout.addWidget(self.button_classify)
        self.settings.addLayout(self.settings_layout)
        self.horizontalLayout_2.addLayout(self.settings)
        self.classificator = QtWidgets.QVBoxLayout()
        self.classificator.setSpacing(6)
        self.classificator.setObjectName("classificator")
        self.classificator_layout = QtWidgets.QVBoxLayout()
        self.classificator_layout.setSpacing(6)
        self.classificator_layout.setObjectName("classificator_layout")
        self.label_section_classification = QtWidgets.QLabel(self.application)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_section_classification.setFont(font)
        self.label_section_classification.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_section_classification.setObjectName("label_section_classification")
        self.classificator_layout.addWidget(self.label_section_classification)
        self.label_input_image = QtWidgets.QLabel(self.application)
        self.label_input_image.setObjectName("label_input_image")
        self.classificator_layout.addWidget(self.label_input_image)
        self.input_image = QtWidgets.QGraphicsView(self.application)
        self.input_image.setObjectName("input_image")
        self.classificator_layout.addWidget(self.input_image)
        self.label_output_image = QtWidgets.QLabel(self.application)
        self.label_output_image.setObjectName("label_output_image")
        self.classificator_layout.addWidget(self.label_output_image)
        self.output_image = QtWidgets.QGraphicsView(self.application)
        self.output_image.setObjectName("output_image")
        self.classificator_layout.addWidget(self.output_image)
        self.classificator.addLayout(self.classificator_layout)
        self.horizontalLayout_2.addLayout(self.classificator)
        minutiae_classificator.setCentralWidget(self.application)
        self.actionNetwork_settings = QtWidgets.QAction(minutiae_classificator)
        self.actionNetwork_settings.setObjectName("actionNetwork_settings")
        self.actionFiles_settings = QtWidgets.QAction(minutiae_classificator)
        self.actionFiles_settings.setObjectName("actionFiles_settings")
        self.actionExtract_minutiae = QtWidgets.QAction(minutiae_classificator)
        self.actionExtract_minutiae.setObjectName("actionExtract_minutiae")
        self.actionClassify_minutiae = QtWidgets.QAction(minutiae_classificator)
        self.actionClassify_minutiae.setObjectName("actionClassify_minutiae")

        self.retranslateUi(minutiae_classificator)
        QtCore.QMetaObject.connectSlotsByName(minutiae_classificator)

    def retranslateUi(self, minutiae_classificator):
        _translate = QtCore.QCoreApplication.translate
        minutiae_classificator.setWindowTitle(_translate("minutiae_classificator", "Minutiae Classificator"))
        self.label_section_settings.setText(_translate("minutiae_classificator", "Settings"))
        self.label_architectures.setText(_translate("minutiae_classificator", "Choose architectures: "))
        self.button_coarse_net.setText(_translate("minutiae_classificator", " CoarseNet architecture"))
        self.button_fine_net.setText(_translate("minutiae_classificator", "FineNet architecture"))
        self.button_classify_net.setText(_translate("minutiae_classificator", "ClassifyNet architecture"))
        self.label_load_network.setText(_translate("minutiae_classificator", "Load neural networks:"))
        self.button_load_network.setText(_translate("minutiae_classificator", "Load Minutiae Classificator"))
        self.label_do_the_job.setText(_translate("minutiae_classificator", "Do the job:"))
        self.button_choose_image.setText(_translate("minutiae_classificator", "Choose minutiae image"))
        self.button_extract.setText(_translate("minutiae_classificator", "Extract minutiae !"))
        self.button_classify.setText(_translate("minutiae_classificator", "Classify minutiae !"))
        self.label_section_classification.setText(_translate("minutiae_classificator", "Classificator"))
        self.label_input_image.setText(_translate("minutiae_classificator", "Input image:"))
        self.label_output_image.setText(_translate("minutiae_classificator", "Output image:"))
        self.actionNetwork_settings.setText(_translate("minutiae_classificator", "Network settings"))
        self.actionFiles_settings.setText(_translate("minutiae_classificator", "Files settings"))
        self.actionExtract_minutiae.setText(_translate("minutiae_classificator", "Extract minutiae"))
        self.actionClassify_minutiae.setText(_translate("minutiae_classificator", "Classify minutiae"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    minutiae_classificator = QtWidgets.QMainWindow()
    ui = Ui_minutiae_classificator()
    ui.setupUi(minutiae_classificator)
    minutiae_classificator.show()
    sys.exit(app.exec_())

